name: udetxen
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1
  google_sign_in: ^6.2.1
  connectivity_plus: ^6.0.5
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  get_it: ^7.7.0
  firebase_messaging: ^15.1.0
  cloud_firestore: ^5.4.1
  flutter_local_notifications: ^17.2.2
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
