// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgMi9jO11ZTJXGBzOjjlGnRef_lmh2Y-8',
    appId: '1:791957746525:web:aaec1b35a3398e164a6eb4',
    messagingSenderId: '791957746525',
    projectId: 'udetxen',
    authDomain: 'udetxen.firebaseapp.com',
    storageBucket: 'udetxen.appspot.com',
    measurementId: 'G-DHMPTX762F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpNixNRcmySrPrds9Lp9kfXJaUErFhc7o',
    appId: '1:791957746525:android:0cbcfe64389db39e4a6eb4',
    messagingSenderId: '791957746525',
    projectId: 'udetxen',
    storageBucket: 'udetxen.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwqDnhzrSEzn8tvtYD0aFgjdQKZipHTLo',
    appId: '1:791957746525:ios:3798e5e93346eb384a6eb4',
    messagingSenderId: '791957746525',
    projectId: 'udetxen',
    storageBucket: 'udetxen.appspot.com',
    iosClientId: '791957746525-33kglm41ooid7sghlha31p168ii9hp4k.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwqDnhzrSEzn8tvtYD0aFgjdQKZipHTLo',
    appId: '1:791957746525:ios:3798e5e93346eb384a6eb4',
    messagingSenderId: '791957746525',
    projectId: 'udetxen',
    storageBucket: 'udetxen.appspot.com',
    iosClientId: '791957746525-33kglm41ooid7sghlha31p168ii9hp4k.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgMi9jO11ZTJXGBzOjjlGnRef_lmh2Y-8',
    appId: '1:791957746525:web:84f3ab8f18e3e05f4a6eb4',
    messagingSenderId: '791957746525',
    projectId: 'udetxen',
    authDomain: 'udetxen.firebaseapp.com',
    storageBucket: 'udetxen.appspot.com',
    measurementId: 'G-TY7XMJK83V',
  );
}
